apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-app-0503
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/neworgyangcao/go-app-0503:8102df9b80e1697520882523bc422a7d56b51051@sha256:9da7a0cf1510661cdb87db3553d93a09a907c52feca47dead121a5566ba90e4b
          name: container-image
